all: build
build:
			(cd Pair; make all)
			(cd Stack; make all)
			(cd List; make all)
			(cd Vec; make all)
			(cd Queue; make all)

clean:
			(cd Pair; make clean)
			(cd Stack; make clean)
			(cd List; make clean)
			(cd Vec; make clean)
			(cd Queue; make clean)
